### ISSUE TITLE
Polling rate and mimimum subscription interval

### ISSUE THREAD

**Issue by JeremyMahieu** [SoftingIndustrial/datafeed-edge-connector#7]
Hello, testing out this software. With a real PLC (Siemens S7-1200) and with the simulation.

- How frequent is the PLC polled (Siemens)? Is this configurable?
- What is the minimum subscription interval? Seems to be 500ms. Why not faster? Configurable?

**Comment by sschenk87** [comment]
Hello @JeremyMahieu 
The subscription inverval from the simulated connection is fixed to 500ms.
To change the OPC UA subscription/polling interval, you just have to create your subscriptions with a faster subscription interval. So if you create the subscriptions with 1000msec, then we will poll the PLC with 1000msec, if you create the subscription with 100msec, we will poll the PLC with 100msec and so on. 
Please be sure, that also the publish interval of your client is also set to the same value, because this is the time, the OPC UA Client visualize the changes.
![1](https://user-images.githubusercontent.com/63799917/128827861-99f3b784-92b8-491a-8823-edcdc67e4a88.png)
![2](https://user-images.githubusercontent.com/63799917/128827864-1d65d99d-64aa-41a8-b9d0-17319d56313a.png)

**Comment by JeremyMahieu** [comment]
We were not able to get this interval lower than 500ms.

**Comment by JeremyMahieu** [comment]
Yes, you're right, it works, thanks again.
